<<<<<<< HEAD
<<<<<<< HEAD

# SEO settings
title: Simplest
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://nandomoreira.me
baseurl: "/simplest"
# baseurl: null

google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/simplest
disqus_shortname: "fernandomoreira"
=======
=======
>>>>>>> parent of fde3c71... Simplest
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
<<<<<<< HEAD
title: Your awesome title
email: your-email@domain.com
=======
title: kobejean.code
email: kobejean.code@gmail.com
>>>>>>> parent of fde3c71... Simplest
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
<<<<<<< HEAD
>>>>>>> parent of 7d37146... Small Adjustments
=======
>>>>>>> parent of fde3c71... Simplest

# Build settings
markdown: kramdown
