<<<<<<< HEAD

# SEO settings
title: kobejean.code
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://nandomoreira.me
baseurl: ""
# baseurl: null

google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/simplest
disqus_shortname: "fernandomoreira"
=======
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
>>>>>>> parent of 7d37146... Small Adjustments

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Jean Flaherty
  job      : Programmer
  bio      : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb    : /images/author.jpg
  email    : kobejean.code.@gmail.com
  #url      : http://nandomoreira.me
  #github   : http://github.com/nandomoreirame
  #twitter  : http://twitter.com/nandomoreirame
  #facebook : http://facebook.com/fernando.dev
  #linkedin : http://linkedin.com/in/nandomoreirame

# social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
#twitter_site: "@nandomoreirame"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
