# Site settings
title: "ML Review"
email: "kobejean@me.com"
description: ""
baseurl: ""
url: "http://kobejean.github.io"
github_username: "kobejean"

# Build settings
markdown: "kramdown"
highlighter: "rouge"
permalink: "pretty"
paginate: 10
timezone: "US/Denver"
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
plugins: ["jekyll-paginate", "jekyll-sitemap"]

kramdown:
  input: GFM
  syntax_highlighter: rouge
